mongo:
    resource: "@MongoBundle/Controller/"
    type:     annotation
    prefix:   /

trello:
    resource: "@TrelloBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
