services:
    trello.client:
        class: AppBundle\Service\TrelloApiFactory
        arguments: [%trello_token%, %trello_secret%]
    
    trello.client.api:
        class: Trello\Client
        factory: ["@trello.client", factory]
        
    trello.lists:
        class: TrelloBundle\Service\ListService
        
    trello.card.moved:
        class: TrelloBundle\Service\CardMovedService
        arguments: ["@trello.client.api"]
